# Generated by Django 3.1 on 2020-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacoes',
            old_name='usuario',
            new_name='user',
        ),
    ]
